name: Create Release on Feature Branch Creation

on:
  create:
    branches:
      - '**feat**'
      - '**feature**'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Branch Name
        id: extract_branch_name
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          echo "Branch Name: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release-${{ env.BRANCH_NAME }}"
          release_name: "Release ${{ env.BRANCH_NAME }}"
          body: |
            Automated release for feature branch: ${{ env.BRANCH_NAME }}
            Changes in this release:
            - Initial release for the feature branch.
          draft: false
          prerelease: true
